baseURL = 'https://blog.mohammadalijf.dev/'
languageCode = 'en-us'
title = 'Mohammadalijf blog'
theme = 'dark-theme-editor'

# Theme Parameters
[params]
    # Parameters applied in HTML <head>
    [params.site]
        # Website ICON
        faviconUrl = ""

        # Do you have any CSS in local? List them in an array.
        # They should be placed inside "/assets" dir.
        # And don't named the file as "index.css" and "style.css".
        # These two files are used by the theme.
        localCss = []

        # Do you need to add any external CSS? List them in an array.
        externalCss = []

        # Do you have any script in local? List them in an array.
        # They should be placed inside "/assets" dir.
        # And don't named the file as "index.js"
        # Theis file is used by the theme.
        localJs = []

        # Do you have any external Script need to add on? List them in an array.
        externalJs = []

    # Customized info shown in header of the page
    [params.header]
        # Website title for header banner.
        title = "Mohammadalijf blog"

        # Subtitle for this site, used in homepage only
        subtitle = "My journey into software engineering"

        # Config about your's site logo, remove this item to hide the logo
        [params.header.logo]
            # Where is your site's URL
            imgUrl = ""

            # If the logo is clickable, where should it be linked?
            # In default, it will linked to the homepage of the site.
            logoLink = ""

    # Customized info shown in footer of the page
    [params.footer]
        # CopyRight string shown in the footer. Keep it an empty string or remove this item will hide it from the page.
        copyrightStr = "All Rights Reserved ®."

        # Should show the counter in the footer or not
        # In the home page, it will show the numbers of all pages
        # In the sections pages, it will show the numbers of pages within the section
        # In the taxonomy pages, it will show the numbers of pages belong to the taxonomy.
        # In the regular content pages, it will show the word count.
        counter = false

        # Should show the language of the page or not
        language = false

        # Should show the hugo version or not
        hugoVersion = false

        # Should show the theme info or not
        theme = false

        # Should show the edited time of the page or not
        modifiedTime = true

        # The format of the `modifiedTime`.
        # Refer to page https://gohugo.io/functions/format/ for more detail.
        # Below is the default format, please do not remove it, unless you set `false` in `modifiedTime` field.
        dateFormat = "Jan 02 2006 15:04:05"

        # Should show the current git HEAD hash or not
        # To make this show up correctly, please follow the prerequisites in page
        # https://gohugo.io/variables/git/
        gitHash = true

        # Social link in the footer, listed items are supported, delete unwanted items to hide it.
        [params.footer.socialLink]
            github = "https://github.com/mohammadalijf"
            facebook = ""
            twitter = "https://twitter.com/mohammadalijf"
            email = ""
            linkedin = "https://www.linkedin.com/in/mohammadali-jafarian-3bb95b71"
            instagram = ""
            telegram = ""
            medium = ""
            vimeo = ""
            youtube = ""

    # Metadata of the site, value will be used in HTML <header>
    # These value would be used when they didn't appear in the frontmatter of a single page.
    # In other words, these value will be overwritten by the frontmatter in the single page.
    [params.globalFrontmatter]
        # The author of this site. This will be shown in 
        # 1. the footer of all page
        # 2. the author filed in the single page. (this could be overwritten by the frontmatter of the single page.)
        # Keep it an empty string or remove this item will hide it from the page
        author = "Mohammadali jafarian"

        # Website description for RSS and SEO. Theme will generate a <meta> tag for this item
        description = "Mohammadalijf blog"

        # Website keywords. Theme will generate a <meta> tag for this item.
        keywords = "software,engineering,blog"

    # Parameters applied in the homepage only
    [params.homePage]
        # Long Descripition shown in home page "Start Block". Is is recommended to have the paragraph shorter than 100 words.        
        siteLongDescription = "Hello there! I'm Mohammadali Jafarian, but you can call me Ali. I'm a software engineer, and on this blog, I aim to share my experiences with various problems, solutions, patterns, principals, and provide my perspective as a software professional. I'll strive to maintain an objective viewpoint on topics, while also noting when I express personal opinions in certain cases."

        # If you don't like the title of "siteLongDescription" be "Start" (default), 
        # you may change the value of this item to "Description" or something you like.
        siteLongDescriptionTitle = "whoami"

        # Param to decide whether to show the most recent blog posts or not. (Default: true)
        showRecentPostsBlock = true

        # Param to decide how many recent posts to show in the home page. (Default: 5)
        numOfRecentPosts = 5

        # Parameter to decide whether to show the URL behind the title.
        # It will be more like an editor if it is shown. However, in general, it can be messy if it is displayed.        
        # (Default: true)
        recentPostShowUrl = false


    # Paramater applied in the single page
    # These values could be overwritten by the frontmatter in the single page.
    [params.page]
        # Should include Table of Content in front of the page or not.
        includeToc = true

        # Should show the author of the page or not.
        # The author name will be shown in the single page if and only if 
        #   1. this items been set as true and
        #   2. "aurthor" filed been provided in the 
        #       A. single page frontmatter or
        #       B. "author" filed in above "globalFrontmatter" block
        showAuthor = false

        # Should show the date of the page or not
        showDate = true

        # The format of the date.
        # Refer to page https://gohugo.io/functions/format/ for more detail.
        # Below is the default format, please do not remove it, unless you set `false` in `showDate` field.
        dateFormat = "2006.01.02"

        # Should show the estimate reading time in front of the page or not.
        showTimeToRead = true

        # Should show the breadcrumb in front of the page or not.
        showBreadcrumb = true
